In [1]:
import numpy as np

In [2]:
lista = [1, 2, 3, 4, 5, 6, 7, 8]
array = np.array(lista)
array 


array([1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
array.sum(), type(array.sum() ) 

(np.int64(36), numpy.int64)

In [5]:
suma_elementelor = int(array.sum())
print(suma_elementelor)

36


In [6]:
print(array.sum())

36


In [7]:
lista = [1, 2, 3, 4, 5, 6, 7, 8]
array = np.array(lista)
array.min(), array.max()

(np.int64(1), np.int64(8))

In [8]:
array.argmin(), array.argmax()

(np.int64(0), np.int64(7))

In [9]:
min(array), max(array), sum(array)

(np.int64(1), np.int64(8), np.int64(36))

In [10]:
array.mean()

np.float64(4.5)

In [11]:
array.shape

(8,)

In [12]:
lista = [1, 2, 3, 4, 5, 6, 7, 8]
array = np.array(lista)
array

array([1, 2, 3, 4, 5, 6, 7, 8])

In [13]:

array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:

array = np.arange(3, 10)
array

array([3, 4, 5, 6, 7, 8, 9])

In [15]:
array = np.arange(3, 30,3)
array

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [ ]:


array = np.array(range(3, 30, 3))
array

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [17]:
array = np.arange(3, 30, 3, dtype=np.float16)
array

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.], dtype=float16)

In [22]:
array = np.arange(9).reshape((3, 3))
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
array = np.arange(9)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [24]:
array * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

In [25]:
array 

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [26]:
array *= 2

In [27]:
array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

In [28]:
array + array

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32])

In [29]:
array = np.arange(100)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [30]:
array % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False])

In [31]:
array_conditie = array % 2 == 0

In [32]:
array[array_conditie]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [33]:
array[array % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [35]:
array = np.arange(100)
array[50:]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [36]:
array = np.arange(100)
array[ array % 7 == 0 ]

array([ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98])

In [39]:


# lista = list(range(100))
# lista[ lista % 7 == 0 ]


In [42]:
array = np.random.randint(-200, 200, 20)
array


array([ 169,  159,   36,    9,   44,  116,  175, -127,   67,  -48,   70,
       -107,  131,  -84,   21,   75,  155,  -18,  -13,   34])

In [43]:
array[ array >= 0 ]

array([169, 159,  36,   9,  44, 116, 175,  67,  70, 131,  21,  75, 155,
        34])

# & - SI LOGIC

In [46]:
array[ (array >= 0) &  (array < 50) ]    

array([36,  9, 44, 21, 34])

In [47]:
pozitive = array >= 0
mai_mici_ca_50 = array < 50

array[ pozitive &  mai_mici_ca_50 ]    

array([36,  9, 44, 21, 34])

In [48]:
array = np.random.randint(-200, 200, 20)
array


array([ -26,  173,   71,  118,   96,    9,  -39, -133,   -9,   84,  181,
       -137,  148,   56, -199,  113,   59,   10,  -40,  134])

# | SAU LOGIC

In [50]:
mai_mici_ca_minus_50 = array < -50
mai_mari_ca_50 = array > 50

array[ mai_mici_ca_minus_50 |  mai_mari_ca_50 ]    




array([ 173,   71,  118,   96, -133,   84,  181, -137,  148,   56, -199,
        113,   59,  134])

In [51]:
array[ (array < -50) |  (array > 50) ] 

array([ 173,   71,  118,   96, -133,   84,  181, -137,  148,   56, -199,
        113,   59,  134])