In [1]:
import numpy as np

In [7]:
start_year = 1800
stop_year = 2025

years = np.arange(start_year, stop_year)
years[:10], years[-10:]

(array([1800, 1801, 1802, 1803, 1804, 1805, 1806, 1807, 1808, 1809]),
 array([2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]))

In [8]:
divizibile_cu_400 = years % 400 == 0
nedivizibile_cu_100 = years % 100 != 0
divizibile_cu_4 = years % 4 == 0

leap_years = years[ divizibile_cu_400 | (nedivizibile_cu_100 & divizibile_cu_4) ]
leap_years

array([1804, 1808, 1812, 1816, 1820, 1824, 1828, 1832, 1836, 1840, 1844,
       1848, 1852, 1856, 1860, 1864, 1868, 1872, 1876, 1880, 1884, 1888,
       1892, 1896, 1904, 1908, 1912, 1916, 1920, 1924, 1928, 1932, 1936,
       1940, 1944, 1948, 1952, 1956, 1960, 1964, 1968, 1972, 1976, 1980,
       1984, 1988, 1992, 1996, 2000, 2004, 2008, 2012, 2016, 2020, 2024])