In [2]:
import numpy as np

In [3]:
np.__doc__

'\nNumPy\n=====\n\nProvides\n  1. An array object of arbitrary homogeneous items\n  2. Fast mathematical operations over arrays\n  3. Linear Algebra, Fourier Transforms, Random Number Generation\n\nHow to use the documentation\n----------------------------\nDocumentation is available in two forms: docstrings provided\nwith the code, and a loose standing reference guide, available from\n`the NumPy homepage <https://numpy.org>`_.\n\nWe recommend exploring the docstrings using\n`IPython <https://ipython.org>`_, an advanced Python shell with\nTAB-completion and introspection capabilities.  See below for further\ninstructions.\n\nThe docstring examples assume that `numpy` has been imported as ``np``::\n\n  >>> import numpy as np\n\nCode snippets are indicated by three greater-than signs::\n\n  >>> x = 42\n  >>> x = x + 1\n\nUse the built-in ``help`` function to view a function\'s docstring::\n\n  >>> help(np.sort)\n  ... # doctest: +SKIP\n\nFor some objects, ``np.info(obj)`` may provide add

In [ ]:
print(np.__doc__)

In [6]:
lista = [1, 2, 3, 4, 5, 6, 7, 9]

In [8]:

array = np.array(lista)
array, type(array)

(array([1, 2, 3, 4, 5, 6, 7, 9]), numpy.ndarray)

In [10]:
matrice = [ [1, 2], [3, 4] ]
array = np.array(matrice)
array, type(array)


(array([[1, 2],
        [3, 4]]),
 numpy.ndarray)

In [11]:
lista = [1, True, 3, 4.3, 5, "Hello", 7, 9]

In [12]:
lista = [1, True, 3, 4.3, 5, "Hello", 7, 9]

array = np.array(lista)
array, type(array)

(array(['1', 'True', '3', '4.3', '5', 'Hello', '7', '9'], dtype='<U32'),
 numpy.ndarray)

In [13]:
lista = [1, True, 3, 4.3, 5,  7, 9]

array = np.array(lista)
array, type(array)

(array([1. , 1. , 3. , 4.3, 5. , 7. , 9. ]), numpy.ndarray)

In [14]:
lista = [1, True, 3, 4.3, 5,  7, 9, [1, 23, 4]]

array = np.array(lista)
array, type(array)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (8,) + inhomogeneous part.

In [17]:
matrice = [ [1, 2, 6], [3, 4, 5] ]
array = np.array(matrice)
array, type(array)


(array([[1, 2, 6],
        [3, 4, 5]]),
 numpy.ndarray)

In [ ]:
matrice = [ [1, 2, 6], [3, 4, 5] ]
array = np.array(matrice)
array, type(array), array.dtype

(array([[1, 2, 6],
        [3, 4, 5]]),
 numpy.ndarray,
 dtype('int64'))

In [20]:
matrice = [ [1, 2, 6], [3, 4, 5] ]
array = np.array(matrice, dtype=np.int8)
array, type(array), array.dtype

(array([[1, 2, 6],
        [3, 4, 5]], dtype=int8),
 numpy.ndarray,
 dtype('int8'))

In [22]:
matrice = [ [1, 2, 6], [3, 4, 127] ]
array = np.array(matrice, dtype=np.int8)
array, type(array), array.dtype

(array([[  1,   2,   6],
        [  3,   4, 127]], dtype=int8),
 numpy.ndarray,
 dtype('int8'))

In [24]:
matrice = [ [1, 2, 6], [3, 4, -128] ]
array = np.array(matrice, dtype=np.int8)
array, type(array), array.dtype

(array([[   1,    2,    6],
        [   3,    4, -128]], dtype=int8),
 numpy.ndarray,
 dtype('int8'))

In [27]:
matrice = [ [1, 2, 6], [3, 4, 255] ]
array = np.array(matrice, dtype=np.uint8)
array, type(array), array.dtype

(array([[  1,   2,   6],
        [  3,   4, 255]], dtype=uint8),
 numpy.ndarray,
 dtype('uint8'))

In [28]:
matrice = [ [1, 2, 6], [3, 4, 256] ]
array = np.array(matrice, dtype=np.uint8)
array, type(array), array.dtype

OverflowError: Python integer 256 out of bounds for uint8